// Generated by CoffeeScript 1.7.1
(function() {
  if (window.js == null) {
    window.js = {};
  }

  window.js.FileDnD = (function() {
    FileDnD.noOp = function() {};

    FileDnD.stopEventBubbling = function(event) {
      event.stopPropagation();
      return event.preventDefault();
    };

    function FileDnD(target, onDrop, onDragging) {
      if (onDragging == null) {
        onDragging = FileDnD.noOp;
      }
      target.on('dragenter', function(event) {
        FileDnD.stopEventBubbling(event);
        return onDragging();
      }).on('dragover', function(event) {
        return FileDnD.stopEventBubbling(event);
      }).on('drop', function(event) {
        var dataTransfer, file, originalEvent, _fn, _i, _len, _ref;
        FileDnD.stopEventBubbling(event);
        originalEvent = event.originalEvent;
        if (originalEvent != null) {
          dataTransfer = originalEvent.dataTransfer;
          if (dataTransfer != null) {
            _ref = dataTransfer.files;
            _fn = function(file) {
              return js.File.readFile(file, onDrop);
            };
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              file = _ref[_i];
              _fn(file);
            }
          } else {
            onDrop({
              message: 'No dataTransfer'
            });
          }
        } else {
          onDrop({
            message: 'No originalEvent'
          });
        }
        return null;
      });
    }

    return FileDnD;

  })();

}).call(this);
