// Generated by CoffeeScript 1.7.1
(function() {
  var test;

  if (window.js == null) {
    window.js = {};
  }

  window.js.Support = (function() {
    function Support() {}

    Support.isArray = Array.isArray || value(function() {
      return {}.toString.call(value === '[object Array]');
    });

    Support.type = function(value) {
      var type_;
      if (value !== void 0 && value !== null) {
        type_ = Object.prototype.toString.call(value);
        type_ = type_.substring(8, type_.length - 1);
        if ((type_ === 'Number') && isNaN(value)) {
          return 'NaN';
        } else {
          return type_;
        }
      } else {
        return String(value);
      }
    };

    Support.merge = function() {
      var key, object, object_, value, _i, _len;
      object = {};
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        object_ = arguments[_i];
        for (key in object_) {
          value = object_[key];
          if (object_.hasOwnProperty(key)) {
            object[key] = value;
          }
        }
      }
      return object;
    };

    return Support;

  })();

  test = function() {
    var method;
    method = function(none) {
      return console.log("none          " + (Support.type(none)));
    };
    method();
    console.log("null          " + (Support.type(null)));
    console.log("Number('a')   " + (Support.type(Number('a'))));
    console.log("1.23          " + (Support.type(1.23)));
    console.log("true          " + (Support.type(true)));
    console.log("'ha'          " + (Support.type('ha')));
    console.log("['ha']        " + (Support.type(['ha'])));
    console.log("{ha:'ha'}     " + (Support.type({
      ha: 'ha'
    })));
    console.log("Math          " + (Support.type(Math)));
    console.log("isArray       " + (Support.type(Support.isArray)));
    console.log("new Date()    " + (Support.type(new Date())));
    console.log("new Support() " + (Support.type(new Support())));
    return console.log("/abc/         " + (Support.type(/abc/)));
  };

}).call(this);
