// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var dom, id, ids, loadContents, noDnD, staged, _i, _len;
    dom = {};
    ids = ['image1', 'image2', 'image3', 'image1_data', 'save', 'title1'];
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      id = ids[_i];
      dom[id] = $("#" + id);
    }
    staged = {};
    noDnD = function(event) {
      event.preventDefault();
      return false;
    };
    $(document.body).on('dragover', noDnD).on('drop', noDnD);
    dom.dropped = $('.dropped');
    dom.dropped.hide();
    loadContents = function(Myid, Myfile) {
      var xmlhttp;
      xmlhttp = void 0;
      if (window.XMLHttpRequest) {
        xmlhttp = new XMLHttpRequest();
      } else {
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
      }
      xmlhttp.onreadystatechange = function() {
        if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
          document.getElementById(Myid).style.background = "url(" + xmlhttp.responseText + ")";
          document.getElementById(Myid).style.content = "url(" + xmlhttp.responseText + ")";
        }
      };
      xmlhttp.open("GET", Myfile, true);
      xmlhttp.send();
    };
    loadContents("image1", "image1.txt");
    dom.image1_data.on("click", function() {
      var onRead;
      onRead = function(file, content) {
        if (js.File.isWebImageType(file.type)) {
          dom.image1.attr({
            style: "background:url(" + content + ") no-repeat center center; background-size:cover;"
          });
          return dom.image1.attr({
            content: content
          });
        }
      };
      return js.File.read(onRead);
    });
    dom.open.on("click", function() {
      var onRead;
      onRead = function(file, content) {
        if (js.File.isTextType(file.type)) {
          return dom.text.text(content);
        }
      };
      return js.File.read(onRead);
    });
    dom.save.click(function() {
      var content;
      content = dom.image1.attr('content');
      js.File.write('image1.txt', content);
      return js.File.write('page_text.txt', dom.title1.text());
    });
    return null;
  });


  /*
    cd "Users/vin/Desktop/course_page/"
    coffee -cwo javascripts/ coffeescripts/
   */

}).call(this);
